Repository Wecloset/pandaFE, pull requests merged in 2023-02, with the labels that each got.

#1 Feat : initial setting
  .eslintrc.js
  .prettierrc.js
  package-lock.json
  package.json
  pages/index.tsx
  src/api/hello.ts
  src/pages/_app.tsx
  src/pages/create/index.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/mypage/index.tsx
  src/pages/search/index.tsx
  src/pages/sign/index.tsx
  src/styles/globals.css
Labels: good first issue

#3 Design : mainlayout, global colors setting
  package-lock.json
  package.json
  public/asset/image/full-logo-white.png
  public/asset/image/full-logo.png
  src/components/layout/layout.tsx
  src/pages/_app.tsx
  tailwind.config.js
Labels: documentation, question

#10 Refactor : Refactor input component
  src/components/input.tsx
  src/pages/create/index.tsx
  src/pages/login/index.tsx
  src/pages/market/[id].tsx
  src/pages/sign/index.tsx
Labels: bug, Add

#15 Design : edit 404, Props sign
  src/components/sign/sign-form.tsx
  src/pages/404.tsx
Labels: bug
